# Configuración de Proyecto SonarCloud para gestion-asistencia-db
sonar.organization=johnjduque
sonar.projectKey=johnjduque_gestion-asistencia-db
sonar.projectName=gestion-asistencia-db
sonar.projectVersion=1.0

# Fuentes a analizar
sonar.sources=.
sonar.inclusions=schema/**/*.sql,*.ps1
sonar.exclusions=scratch/**,test/**,docs/**

# Codificación
sonar.sourceEncoding=UTF-8
