# Configuración de Proyecto SonarQube para gestionasistenciadb
sonar.projectKey=gestion-asistencia-db
sonar.projectName=Gestion Asistencia DB
sonar.projectVersion=1.0

# Fuentes a analizar
sonar.sources=.
sonar.inclusions=schema/**/*.sql,*.ps1
sonar.exclusions=scratch/**,test/**,docs/**

# Codificación
sonar.sourceEncoding=UTF-8
